config_file = open('/media/steffen/boot/config.txt', 'a')
config_file.write('\nhdmi_force_hotplug=1\n')
config_file.write('hdmi_group=2\n')
config_file.write('hdmi_mode=87\n')
config_file.write('hdmi_cvt=800 480 60 6 0 0 0\n')
config_file.write('hdmi_drive=1\n')
