#! /bin/bash

#include config file:
. /etc/soaribox/soaribox.conf

# Write bootup to log file
echo "$(date): Booting up OpenMaStAr." >> $SOARILOG/soaribox.log



# Start OGN if activated in config file

if [ $CARDAVOGN -gt 0 ]
then
	echo "OGN Card available -> starting SoftRF" >> $SOARIHOME/soaribox.log
	/bin/stty -F $SERIAL 9600 raw &
	{ echo "{class:SOFTRF,protocol:"$SOFTRFPROT"}" ; /bin/cat $SERIAL ; } | $SOARIHOME/softrf/SoftRF $ARGSOFTRF | /bin/netcat -l 10110 -k 
	echo "OGN Card sucessfully started" >> $SOARIHOME/soaribox.log

else
	echo "OGN Card not available" >> $SOARIHOME/soaribox.log
fi

# Start Fuse if activated


# Start XCSOAR

if [ $STARTXCSOAR -gt 0 ]
then
	 echo "Xcsoar Startup active -> Starting now" >> $SOARIHOME/soaribox.log
#	/usr/bin/xcsoar
	python $SOARIHOME/Start_SoariBox.py
else
	 echo "Xcsoar Startup deactivated" >> $SOARIHOME/soaribox.log
fi
